# fly.toml app configuration file generated for app-reactivities on 2023-09-06T13:15:57+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "app-reactivities"
primary_region = "cdg"

[build]
  image = "tomershaw/reactivities:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  Cloudinary__CloudName="dkhj9nflm"
  Cloudinary__ApiKey="211527574944433"


[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
